# Site settings
name: Think Deep,Work Lean
email: zhangkaiamm@gmil.com
author: Kaiz
url: https://kaizamm.github.com
resume_site: 
github: https://github.com/kaizamm
baseurl: 
description: Actually, less is more!
meta_description: 张凯:学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: kaizamm

# Build settings
markdown: kramdown

baidu_analysis: a81273dded286ab83c533a4184e6ae8c

